// Bundles the browser client for `ruddr web` at development time. The Rust
// server embeds the output, so Bun is a development dependency only.
//
//   bun scripts/build-web.ts          rebuild crates/ruddr-web/assets
//   bun scripts/build-web.ts --check  exit 1 when the committed bundle is stale
//
// Outputs, all committed:
//   crates/ruddr-web/assets/client/   the Bun.build output (index.html, chunks)
//   crates/ruddr-web/assets/bundle.rs the embedded file table
//   crates/ruddr-web/assets/SOURCE_HASH  the hash of the bundle inputs
//   crates/ruddr-web/assets/themes.json and fallback-models.json, copied from
//     tui/themes.ts and tui/core.ts while those sources exist
//
// The Rust test `bundle_matches_sources` recomputes SOURCE_HASH the same way
// and fails when web/client changed without a rebuild.
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

const repo = join(import.meta.dir, "..");
const assets = join(repo, "crates", "ruddr-web", "assets");
const clientOut = join(assets, "client");

/** Bundle inputs, as repository-relative paths with forward slashes. */
async function inputFiles(): Promise<string[]> {
  const files = ["web/index.html", "scripts/build-web.ts"];
  const walk = async (directory: string) => {
    for (const entry of await readdir(join(repo, directory), { withFileTypes: true })) {
      const path = `${directory}/${entry.name}`;
      if (entry.isDirectory()) await walk(path);
      else if (entry.isFile() && !entry.name.endsWith(".test.ts")) files.push(path);
    }
  };
  await walk("web/client");
  return files.sort();
}

/**
 * sha256 over one line per input: `path NUL sha256(content) LF`, in byte
 * order of the path. Content has CRLF folded to LF so a Windows checkout
 * hashes the same. The pinned @pierre dependency versions count as one more
 * input named `package.json#@pierre`.
 */
export async function sourceHash(): Promise<string> {
  const entries: Array<[string, Buffer]> = [];
  for (const path of await inputFiles()) {
    const text = (await readFile(join(repo, path))).toString("latin1").replaceAll("\r\n", "\n");
    entries.push([path, Buffer.from(text, "latin1")]);
  }
  const manifest = JSON.parse(await readFile(join(repo, "package.json"), "utf8")) as { dependencies?: Record<string, string> };
  const pierre = Object.entries(manifest.dependencies ?? {})
    .filter(([name]) => name.startsWith("@pierre/"))
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([name, version]) => `${name}@${version}\n`)
    .join("");
  entries.push(["package.json#@pierre", Buffer.from(pierre, "utf8")]);
  entries.sort(([a], [b]) => Buffer.compare(Buffer.from(a), Buffer.from(b)));
  const outer = createHash("sha256");
  for (const [path, content] of entries) {
    outer.update(`${path}\0${createHash("sha256").update(content).digest("hex")}\n`);
  }
  return outer.digest("hex");
}

async function build(): Promise<void> {
  // These options match what web/server.ts used at startup.
  const result = await Bun.build({
    entrypoints: [join(repo, "web", "index.html")],
    minify: true,
    splitting: true,
    target: "browser",
    naming: { entry: "[name].[ext]", chunk: "chunks/[name]-[hash].[ext]", asset: "assets/[name]-[hash].[ext]" },
  });
  if (!result.success) throw new Error(result.logs.map((log) => String(log)).join("\n") || "web client build failed");
  await rm(clientOut, { recursive: true, force: true });
  const rows: string[] = [];
  let index = "";
  for (const output of result.outputs) {
    const path = output.path.replace(/^\.\//, "");
    const target = join(clientOut, path);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, new Uint8Array(await output.arrayBuffer()));
    const type = output.type || "application/octet-stream";
    if (output.kind === "entry-point" && path.endsWith(".html")) index = `/${path}`;
    rows.push(`    (${JSON.stringify(`/${path}`)}, ${JSON.stringify(type)}, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), ${JSON.stringify(`/assets/client/${path}`)}))),`);
  }
  if (!index) throw new Error("the web client build produced no HTML entry point");
  rows.sort();
  const table = `// Generated by scripts/build-web.ts. Do not edit.
/// The HTML entry point among FILES.
pub const INDEX_PATH: &str = ${JSON.stringify(index)};

/// Every bundled file: URL path, content type, bytes.
pub const FILES: &[(&str, &str, &[u8])] = &[
${rows.join("\n")}
];
`;
  await writeFile(join(assets, "bundle.rs"), table);

  if (existsSync(join(repo, "tui", "themes.ts"))) {
    const { themes } = await import(join(repo, "tui", "themes.ts"));
    await writeFile(join(assets, "themes.json"), `${JSON.stringify(themes, null, 1)}\n`);
  }
  if (existsSync(join(repo, "tui", "core.ts"))) {
    const { FALLBACK_MODELS } = await import(join(repo, "tui", "core.ts"));
    await writeFile(join(assets, "fallback-models.json"), `${JSON.stringify(FALLBACK_MODELS, null, 1)}\n`);
  }
  await writeFile(join(assets, "SOURCE_HASH"), `${await sourceHash()}\n`);
  const total = result.outputs.reduce((sum, output) => sum + output.size, 0);
  console.log(`Bundled ${result.outputs.length} files (${(total / 1024 / 1024).toFixed(1)} MiB) into ${relative(repo, clientOut)}`);
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const recorded = existsSync(join(assets, "SOURCE_HASH")) ? (await readFile(join(assets, "SOURCE_HASH"), "utf8")).trim() : "";
    const current = await sourceHash();
    if (recorded !== current) {
      console.error(`The web client bundle is stale (recorded ${recorded || "none"}, sources ${current}); run bun scripts/build-web.ts`);
      process.exit(1);
    }
    console.log("The web client bundle matches web/client");
  } else {
    await build();
  }
}
